### ISSUE TITLE
Is the overlay still active?

### ISSUE THREAD

**Issue by ghost** [BilyakA/gentoo-clang#2]
I've migrated my boxes to llvm/clang/libcxx system-wide, and I have some patches that I maintain in my local repo. So I would like to contribute if the overlay are still active.

**Comment by BilyakA** [comment]
Hi, @ian-moone 
Yeah, overlay is still alive, but unfortunately, I do not have much time to keep it updated.
I would appreciate any contribution

**Comment by ghost** [comment]
Great, I'm glad to hear that. I'll be contributing soon.

**Comment by ghost** [comment]
In the future, if you trust me enough, of course, you can add me as a collaborator, so I will not overwhelm you with too many PRs for review. I'm also [an overlay](https://gitlab.com/chaoslab/chaoslab-overlay) maintainer, at least you can rest assured that you will not waste time teaching me the basics.

**Comment by BilyakA** [comment]
@ian-moone I have overlooked your PRs, everything looks good to me, but I haven't had enough time to test everything, so I just trust you :) .
Anyway I am very happy that I am not alone
I am going to give you collaborator rights of course.
But before that just some notes about this overlay (I think I should add this in Readme later):
1) we are not going to add any new packets that are not in main tree until it is completely necessary 
2) all patches must not break compilation on GCC or anything else.
3) MAYBE we will add new versions of LLVM/Clang/lld/etc. to stay in front of main tree if it will be behind of stable releases for long time

**Comment by ghost** [comment]
> ... so I just trust you :) 
> ...
> I am going to give you collaborator rights of course.

Thank you. I really appreciate that. I'll do my best to keep your trust, but of course, actions means more than words.

BTW, any change that would involve some doubts, or requires further discussions, I will make a PR, instead of committing directly. 

>  1. we are not going to add any new packets that are not in main tree until it is completely necessary

Understood. This is similar to libressl overlay. Where there we just sync/patch up packages in main tree.

Perhaps in the future, we should create a sister overlay, let's say `clang-extras`, where we could put experimental stuff and packages not in main tree.

> 2. all patches must not break compilation on GCC or anything else.

Sure thing.

> 3. MAYBE we will add new versions of LLVM/Clang/lld/etc. to stay in front of main tree if it will be behind of stable releases for long time

👍
