### ISSUE TITLE
ERROR: Unknown command line option '-no-xcb-xinput'. 

### ISSUE THREAD

**Issue by RevySR** [BilyakA/gentoo-clang#6]
In Qt 5.15, the optional '-no-xcb-xinput' is rename '-no-bundled-xcb-xinput'

[proj/qt.git](https://cgit.gentoo.org/proj/qt.git/tree/eclass/qt5-build.eclass?id=b079ea36e17142375e80500155369cfb973e3ea7#n576)

**Comment by RevySR** [comment]
The optional '-no-xkb' is deleted

[proj/qt.git](https://cgit.gentoo.org/proj/qt.git/tree/eclass/qt5-build.eclass?id=b079ea36e17142375e80500155369cfb973e3ea7#n624)

**Comment by BilyakA** [comment]
Everything from Qt 5.15 is still in testing and normally I check only latest stable ebuilds.
Anyway you are right, my qt5-build.eclass is far behind from upstream. I'll update it ASAP
