### ISSUE TITLE
noted /etc/portage git sub

### ISSUE THREAD

**Issue by necrose99** [BilyakA/gentoo-clang#7]
git push .... 

RPI3 or 4 / rock64 sbc's 
github repo **arm64-portage** , @necrose99 

anyway trying to not snap gentoo clangs git if thats the case , and add its tracking etc. to current git... 
rpi4 has been griping  over git-submodule/s were before i hadn't 

ever is it nice to pull repo clone fix on local laptop git push , ssh/git pull or etc.. 

hopefully soon docker.. 

https://github.com/InBetweenNames/gentooLTO  while it has a few nice ideals... 
adding it with gentoo-clang can on arch64 yeaild emerge fooo:overlay going catywampus or other strang... 

hopefully some clang into it as a further refinements ... as clang tends to make for simpler arch-64 crossing and ore etc. 

hopefully can add clang as opts..

**Comment by BilyakA** [comment]
not sure if I have understood you correctly...

So you are trying to `git submodule` gentoo-clang into your arm64-portage repo, right? 
What went wrong with that? And why don't you use layman?

**Comment by necrose99** [comment]
mainly /etc/kernels > /etc/portage/kernels  configs valted. 
package masks uses make.conf/s i sync to gh....  anyhow can keep uses etc's all more constant.. 

_git push origin/all .... enter the gh creds..._   add keybase.... gpg.... gruble...grumble to new ins.....tall. grumble.. 
 
**ERROR gentoo-clang submodule ????**
 *news to me...  not sure if the "sub module" ???  
what has my etc portage github .... benn toking... or why broken ... 
:well its aarch64 more broken than usual.. :
**Stange Error this is...**  clang sub module ??? 
<img src="https://420problems.com/wp-content/uploads/2019/12/37082/only-the-best-weedmeme-weedstagram420-weedhumor-weedporn-weedmemes-weed-memesdaily-meme-marijuanamemes-marijuanameme-marijuana.jpg" height="150" width="250" alt="what kida weed did you say this was,">



 **_gentoo-clang's overlay tooling  uses git_** ... internally for... ??? 
**if this be the case , just trying to respect/.gitignore  its git and <blink>not clobber it.**</blink>  of gentoo-clangs uses etc added to etc portage.. via git int locally..  
WHAT the ? is why i ask. 


with **3-4 SBC's** if sdcard goes fubar least packages and configs are saved.  as well github desktop or the Linux GitHub desktop fork and x11 [https://github.com/shiftkey/desktop/releases](https://github.com/shiftkey/desktop/releases)
 is none to bad at fixing config file error ngnix or libree office with a gazzlion use flags ... 
or sys-devel_gcc , bla bla > sys-devel.... combined. 
also makes syncing /etc/portage to rpi4-desktop , rpi4-worker , rock64pro rpi3 etc a sinch. 

trying fo a mini docker cluster of arrch64 fun..  and hopefully if i can learn just enough devops foo /drone-cli can bake pentesting toys

**Comment by BilyakA** [comment]
Again: not sure I have understood you correctly...

You are working with your /etc/portage repo with all configs for AArch64 and somehow it now conflicts with my gentoo-clang overlay? 

Can you show or at least copy-paste the error and a way to reproduce it here? Maybe I will understand your problem that way...

**Comment by necrose99** [comment]
i have /etc/portage point to github  ie RPI-4 , single board computers.... 
(so editing configs can be done on laptop /also makes easier to un-fuck shit if you fail at X... esp since not on mail linux desktop.. x64 ..  and ssh fails. 
ok sweet..)


_installed gentoo-clang packages ...  added eclass overrides... followed wiki..._ 

bla bla bla is deprecated.....  (a few old arcane versions  packages to were masks are so old portage gripes... as no longer in tree./or what have use 
 fat fringed use flags or other cruft i've been meaning to tidy up. )

_fix over ssh_ 

**git push** ....... (enter gh creds) 

### git sub modules gentoo-clang .......  / ER? What the fu-hell ?????? / where ??? the hell this come into ??? 

**RANDOM error** ???? I dunno , it could be a random error or some weirdness i need to fix.. 

why exactly  (git sub modules gentoo-clang)  ??? 
is some of the /etc/portage items added tracked via its own git. ? ??? 
could be just some random gremlin/ghost in the shell. 


### **long and sort of it :  I got a very strange error** ,
 that has me asking is /etc/portage bits from gentoo-clang using git ?   
or just added via emerge..  **app-portage/ltolize**  took a look at gentoo-lto .as well..   however looks more .... unstable to aaarch64 atm... not many clang options in it either...  and might not be to healthy.... for now...  if i mix the 2.. 



 if so i can pull files  to laptop n burn /etc/portage on rpi4-desktop 
add fixes to gh... ,etc... 
**kill the were the were the hell came from ??? submodule ...** 

(git clone /etc/portage down...  cause editing 6 gazillion  use flags again on 3--4 devices is a pain in the ass.. 
layman/esel...repo...  on 1 /copy past same to others) 

### (added systemd branch to split rock64pro chroot-systemd , move changes  make.conf +systemd , else use flags copy paste git push... _ )   


it could be the crappy wifi home 7 year old  router i just Finally kicked to curb , along with the **random ssh fail ferry** granting random gremlins to stuff than need'n't be.  when the connection severs...   _who knows what the gremlins are typing when the ssh drops..._suddenly   ) 

## if thats the case its a random Gremlin , 


**steps to reproduce??** : , vault iot crap ie aarch64  or Arduino configs to github  sdcards can flake out and die..  so a back up stratagem to not lose configs. /backup bin-pkg tarballs... 

RPI-cluster or Arduino for kicks... or etc..  muck with gentoo-lto/gentoo-clang for cleaner more compact...  , random fail Gremlins creep in.... 
 
### **steps to reproduce??**   it may not even be reproduce-able and random chance of an error. 

if thats the case i need not feed and water the RPI-'s after midnight (har har) cause Gremlins ya'know it.. 
n will have to just un-bork stuff..  


ok time to snag the pull  and un-bork this weirdness.

**Comment by necrose99** [comment]
yeah im cleaning them out the Fs image started going fubar  some how the area of disk went catywampus. 

been re-doing them and cleaning out curfted old configs ,
